"use client";

import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import store from "./redux/Store";
import BarComponents from "./components/Bar";
import { useEffect } from "react";
import { setGoogleLogin, setSummaristLogin, setGuestLogin } from "./redux/User";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

const metadata: Metadata = {
  title: "summarist.Ramirez",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  useEffect(() => {
    const storedUser = localStorage.getItem("user");
    const loginType = localStorage.getItem("loginType");

    if (storedUser && loginType) {
      const user = JSON.parse(storedUser);

      if (loginType === "google") {
        store.dispatch(setGoogleLogin(user));
      } else if (loginType === "summarist") {
        store.dispatch(setSummaristLogin(user));
      } else if (loginType === "guest") {
        store.dispatch(setGuestLogin(user));
      }
    }
  }, []);

  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <Provider store={store}>
          <BarComponents />
          {children}
        </Provider>
      </body>
    </html>
  );
}
